public class AreaOfFigures {

    public void Figure(integer area){
system.debug('Area of square '+area*area);
        
    }
    public void Figure(integer length, integer breth){
system.debug('Area of Rectangle '+length*breth);
        
    }
    public void Figure(decimal breth,integer height){
        decimal triangle=breth*height/2;
system.debug('Area of Triangle '+triangle);
        
    }
    
}